######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/images/logo/logo.png"
logo_on_black: "/images/logo/logo.png"
custom_js: ["js/custom.js"]
custom_css: ["css/custom.css"]

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: []

github:
  repo_url: "https://github.com/lidaof/smaht-donor/blob/master"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: "https://www.facebook.com/profile.php?id=100091872325711"
  flickr: ""
  github: ""
  instagram: "https://www.instagram.com/smahtnetwork/"
  landscape: ""
  linkedin: "https://www.linkedin.com/groups/14287460/"
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: "https://x.com/SMaHTnetwork"
  youtube: "https://www.youtube.com/@SMaHTnetwork"

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false
